# Generated by Django 3.2.12 on 2022-02-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_user_emisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigoAuxiliar',
            field=models.CharField(db_column='pro_auxiliar', max_length=20, unique=True, verbose_name='Código auxiliar'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigoPrincipal',
            field=models.CharField(db_column='pro_principal', max_length=20, unique=True, verbose_name='Código principal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_column='pro_nombre', max_length=250, unique=True, verbose_name='Nombre'),
        ),
    ]
