# Generated by Django 3.2.12 on 2022-03-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20220224_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadetalle',
            name='factura',
            field=models.ForeignKey(db_column='det_factura', on_delete=django.db.models.deletion.CASCADE, related_name='facturaDetalle', to='ventas.facturacabecera', verbose_name='Factura cabecera'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='factura',
            field=models.ForeignKey(db_column='fpa_factura', on_delete=django.db.models.deletion.PROTECT, related_name='forma_pago', to='ventas.facturacabecera', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='notaDebito',
            field=models.ForeignKey(db_column='fpa_nota_debito', on_delete=django.db.models.deletion.PROTECT, related_name='forma_pago_nd', to='ventas.notadebito', verbose_name='Nota debito'),
        ),
        migrations.AlterField(
            model_name='otro',
            name='factura',
            field=models.ForeignKey(db_column='otr_factura', on_delete=django.db.models.deletion.CASCADE, related_name='otro', to='ventas.facturacabecera', verbose_name='Factura'),
        ),
    ]
