# Generated by Django 3.2.12 on 2022-03-25 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0004_auto_20220301_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapago',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='formapago',
            name='notaDebito',
        ),
        migrations.RemoveField(
            model_name='formapago',
            name='plazo',
        ),
        migrations.RemoveField(
            model_name='formapago',
            name='tiempo',
        ),
        migrations.RemoveField(
            model_name='formapago',
            name='valor',
        ),
        migrations.AlterField(
            model_name='formapago',
            name='codigo',
            field=models.CharField(blank=True, db_column='fpa_codigo', default='', max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='FormaPagoNotaDebito',
            fields=[
                ('id', models.AutoField(db_column='fpn', primary_key=True, serialize=False, verbose_name='Id')),
                ('plazo', models.IntegerField(blank=True, db_column='fpn_plazo', null=True, verbose_name='Plazo')),
                ('valor', models.FloatField(blank=True, db_column='fpn_valor', null=True, verbose_name='Valor')),
                ('forma_pago', models.ForeignKey(db_column='fpn_forma_pago', on_delete=django.db.models.deletion.PROTECT, to='ventas.formapago')),
                ('nota_debito', models.ForeignKey(db_column='fpn_nota_debito', on_delete=django.db.models.deletion.PROTECT, to='ventas.notadebito')),
                ('usuario', models.ForeignKey(db_column='fpn_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forma de pago Nota de Debito',
                'verbose_name_plural': 'Formas de pago Nota de Debito',
            },
        ),
        migrations.CreateModel(
            name='FormaPagoFactura',
            fields=[
                ('id', models.AutoField(db_column='fpf_id', primary_key=True, serialize=False, verbose_name='Id')),
                ('tiempo', models.IntegerField(blank=True, db_column='fpf_tiempo', null=True, verbose_name='Tiemmpo')),
                ('plazo', models.IntegerField(blank=True, db_column='fpf_plazo', null=True, verbose_name='Plazo')),
                ('valor', models.FloatField(blank=True, db_column='fpf_valor', null=True, verbose_name='Valor')),
                ('facturaid', models.ForeignKey(db_column='fpf_factura', on_delete=django.db.models.deletion.PROTECT, related_name='forma_pago_factura', to='ventas.facturacabecera', verbose_name='Factura')),
                ('formaPago', models.ForeignKey(db_column='fpf_forma_pago', on_delete=django.db.models.deletion.PROTECT, to='ventas.formapago', verbose_name='Forma de pago')),
                ('usuario', models.ForeignKey(db_column='fpf_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forma de pago factura',
                'verbose_name_plural': 'Formas de pago de factura',
            },
        ),
    ]
