# Generated by Django 3.2.12 on 2022-03-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20220329_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacabecera',
            name='valorIva',
        ),
    ]
