# Generated by Django 3.2.12 on 2022-03-29 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_remove_facturacabecera_valoriva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapago',
            options={'verbose_name': 'Forma de pago', 'verbose_name_plural': 'Formas de pago'},
        ),
        migrations.AlterModelOptions(
            name='otrondnc',
            options={'verbose_name': 'Otro N/D o N/C', 'verbose_name_plural': 'Otros N/D o N/C'},
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='factura',
            field=models.ForeignKey(db_column='det_factura', on_delete=django.db.models.deletion.CASCADE, related_name='factura_detalle', to='ventas.facturacabecera', verbose_name='Factura cabecera'),
        ),
        migrations.AlterField(
            model_name='otro',
            name='factura',
            field=models.ForeignKey(db_column='otr_factura', on_delete=django.db.models.deletion.CASCADE, related_name='otro_factura', to='ventas.facturacabecera', verbose_name='Factura'),
        ),
    ]
