# Generated by Django 3.2.12 on 2022-04-01 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_facturadetalle_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='cliente',
            field=models.ForeignKey(db_column='ncr_cliente', default=1, on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='formapagonotadebito',
            name='nota_debito',
            field=models.ForeignKey(db_column='fpn_nota_debito', on_delete=django.db.models.deletion.PROTECT, related_name='forma_pago_debito', to='ventas.notadebito'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='estado',
            field=models.CharField(choices=[('1', 'Generado'), ('2', 'Anulado')], db_column='ncr_estado', default='1', max_length=5, verbose_name='Estado'),
        ),
    ]
