# Generated by Django 3.2.12 on 2022-04-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_auto_20220401_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenc',
            name='notaCredito',
            field=models.ForeignKey(db_column='dnc_nota_credito', on_delete=django.db.models.deletion.CASCADE, related_name='detalle_nota_credito', to='ventas.notacredito', verbose_name='Nota de crédito'),
        ),
        migrations.AlterField(
            model_name='detallenc',
            name='producto',
            field=models.ForeignKey(db_column='dnc_producto', on_delete=django.db.models.deletion.CASCADE, related_name='producto_nota_credito', to='ventas.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='otrondnc',
            name='notaCredito',
            field=models.ForeignKey(db_column='odc_nota_credit', null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.notacredito', verbose_name='Nota de crédito'),
        ),
        migrations.AlterField(
            model_name='otrondnc',
            name='notaDebito',
            field=models.ForeignKey(db_column='odc_nota_debito', null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.notadebito', verbose_name='Nota de debito'),
        ),
    ]
