# Generated by Django 3.2.12 on 2022-04-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_auto_20220405_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencioncodigo',
            name='tipo',
            field=models.CharField(choices=[('iva', 'I. V. A.'), ('renta', 'Renta')], db_column='rco_tipo', max_length=20, verbose_name='Tipo'),
        ),
    ]
