# Generated by Django 3.2.12 on 2022-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_alter_retencioncodigo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencioncodigo',
            name='codigo',
            field=models.CharField(db_column='rco_codigo', max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
