# Generated by Django 3.2.12 on 2022-04-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_alter_retencioncodigo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencion',
            name='secuencia',
            field=models.IntegerField(db_column='ret_secuencia', verbose_name='Secuencia'),
        ),
    ]
