# Generated by Django 3.2.12 on 2022-04-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_alter_retencion_secuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencioncompra',
            name='retencion',
            field=models.ForeignKey(db_column='rcp_retencion', on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_compra', to='ventas.retencion', verbose_name='Retención'),
        ),
        migrations.AlterField(
            model_name='retencioncompra',
            name='retencion_codigo',
            field=models.ForeignKey(db_column='rcp_retencion_codigo', on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_codigo', to='ventas.retencioncodigo', verbose_name='Código de retención'),
        ),
    ]
