# Generated by Django 3.2.12 on 2022-04-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_auto_20220406_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencioncompra',
            name='retencion_codigo',
            field=models.ForeignKey(db_column='rcp_retencion_codigo', on_delete=django.db.models.deletion.PROTECT, to='ventas.retencioncodigo', verbose_name='Código de retención'),
        ),
    ]
