# Generated by Django 3.2.12 on 2022-04-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_alter_retencioncompra_retencion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencion',
            name='autorizacion',
            field=models.CharField(blank=True, db_column='ret_autorizacion', max_length=49, null=True, verbose_name='Autorización'),
        ),
        migrations.AlterField(
            model_name='retencion',
            name='clave_acceso',
            field=models.CharField(blank=True, db_column='ret_clave_acceso', max_length=49, null=True, verbose_name='Clave de acceso'),
        ),
    ]
