# Generated by Django 3.2.12 on 2022-04-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_alter_emisor_ambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='autorizacion',
            field=models.CharField(blank=True, db_column='ncr_autorizacion', max_length=49, null=True, verbose_name='Autorización'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='claveacceso',
            field=models.CharField(blank=True, db_column='ncr_claveacceso', max_length=49, null=True, verbose_name='Clave de acceso'),
        ),
    ]
