# Generated by Django 3.2.12 on 2022-04-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_auto_20220408_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notadebito',
            name='autorizacion',
            field=models.CharField(blank=True, db_column='nde_autorizacion', max_length=49, null=True, verbose_name='Autorización'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='claveacceso',
            field=models.CharField(blank=True, db_column='nde_claveacceso', max_length=49, null=True, verbose_name='Clave de acceso'),
        ),
    ]
