# Generated by Django 3.2.12 on 2022-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_auto_20220408_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoIdentificacion',
            field=models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor final'), ('08', 'Identificación del exterior')], db_column='cli_tipo_identificacion', default='sn', max_length=5, verbose_name='Tipo de identificación'),
        ),
    ]
