# Generated by Django 3.2.12 on 2022-04-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0024_alter_cliente_tipoidentificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='iva',
            name='codigo',
            field=models.CharField(db_column='iva_codigo', default='', max_length=2, verbose_name='Código'),
        ),
    ]
